### ISSUE TITLE
Remove Emissions Statement app

### ISSUE THREAD

**Issue by dougwaldron** [gaepdit/geco#586]
Requested via email and [Zendesk](https://gaepd.zendesk.com/agent/tickets/15479):

> As of June 19, 2023, we removed the requirement of submitting ES. For Emissions Statement application at GECO, we recommend removing the ES link and state the following message in the current status box:
> 
> ![image](https://github.com/gaepdit/geco/assets/737326/f5dc0853-54f5-445e-a056-7effd97a3ee7)
> 
> For Emissions Statement Application at GECO, it can be invisible in the future, like from 2025 on.
> 
> For Emissions Statement tool in IAIP, we can leave it alone since it captured the past ES data.
> 
> Let me know if you have any questions related to this request. 

---

```[tasklist]
### Tasks
- [x] Remove internal ES pages
- [x] Disable link on facility home page
- [x] Remove ES description from home page (logged in and not logged in)
- [x] Remove ES permissions column from user home page
- [x] Remove ES permissions from facility user access page (check with APB about this)
- [x] Remove ES contact from facility contacts configuration
- [x] Remove ES from facility access request form
```
