### ISSUE TITLE
EI updates for 2023

### ISSUE THREAD

**Issue by dougwaldron** [gaepdit/geco#593]
Requested via email and [Zendesk](https://gaepd.zendesk.com/agent/tickets/16591):

> For 2023 EI reporting, we plan to have EI kickoff training on Dec. 13, so we need your assistance to have a few updates on GECO. Please see attachment for detail.
```[tasklist]
### Tasks
- [x] Reorganize GECO EIS page
- [x] Fix layout of IAIP EIS tool
- [x] Add CAERS users to IAIP facility summary contacts
- [x] Start enrollment earlier
- [x] Update ES link
- [x] Change document links/buttons
- [x] Update opt-out form
- [x] Number the sections on the GECO EIS page
- [x] Require letters in name in GECO contacts form
```

**Comment by dougwaldron** [comment]
Sent to Tamika for QA

**Comment by dougwaldron** [comment]
QA updates:

* IAIP Dev says it is temporarily down
* Unicode character issue on Edit CAERS Users page

**Comment by dougwaldron** [comment]
> * IAIP Dev says it is temporarily down

IAIP Dev version is too old. Will update when ready for QA.

> * Unicode character issue on Edit CAERS Users page

Fixed in DEV

**Comment by dougwaldron** [comment]
Additional requests received this morning (added to tasklist above).

**Comment by dougwaldron** [comment]
Sent all changes to ECSU for UAT.

**Comment by dougwaldron** [comment]
Additional requests received this morning (added to tasklist above).

**Comment by dougwaldron** [comment]
Additional requests received yesterday; added to tasklist.

**Comment by dougwaldron** [comment]
Previous changes were all approved. One additional request received yesterday.
