### ISSUE TITLE
Prepare GECO for 2024 Emissions Inventory

### ISSUE THREAD

**Issue by dougwaldron** [gaepdit/geco#612]
Requested via email:

> The Point Source EI team is close to completing the 2023 EI submission and has started planning for 2024. We’re aiming to have the 2024 EI kickoff training on December 11, with all facilities enrolled by December 9. The GECO EI for 2024 should also be ready by December 9.

```[tasklist]
### Tasks
- [x] Upload new opt-out form.
- [x] Revise GECO based on the document submitted with the email.
- [ ] Populate the EI facility universe the week of December 2.
```

**Comment by dougwaldron** [comment]
Sent GECO updates to ECSU for UAT.
